name: Rust

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set git version
      run: echo "GIT_VERSION=$(git.exe rev-parse --short HEAD)" >> $env:GITHUB_ENV

    - name: Build
      run: cargo build --release

    - name: Pack Release files
      run: |
        Copy target/release/lutdinho.exe ./lutdinho.exe
        tar -a -c -f lutdinho.zip lutdinho.exe

    - name: Set Release version
      run: echo "TAG_VERSION=$(python get_version.py)" >> $env:GITHUB_ENV
    - name: "Automatic Release"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.TAG_VERSION }}"
        prerelease: false
        title: "${{ env.TAG_VERSION }}"
        files: |
          lutdinho.zip
